#!/bin/bash

docker-agent-sshd-stop() {
    docker stop docker-agent &>/dev/null
    docker rm docker-agent &>/dev/null
}

docker-agent-sshd-start() {
    docker run \
           --name=docker-agent \
           --rm \
           -d \
           --init=true \
           -p 22 \
           -v "docker-agent-tmp:/tmp" \
           -v "$HOME/.ssh/id_rsa.pub:/root/.ssh/authorized_keys" \
           dobbs/docker-agent \
           /usr/sbin/sshd -D \
           &> /dev/null

    local ssh_port=$(
        docker port docker-agent 22/tcp \
            | grep -oE '[[:digit:]]+$'
          )

    printf "%s\n" "$ssh_port"
}

docker-agent-sshd-status() {
    local msg=''
    if docker ps --filter=name=docker-agent | grep -q docker-agent; then
        msg='docker-agent sshd is running'
    else
        msg='docker-agent sshd is not running'
    fi
    printf "%s\n" "$msg"
}

docker-agent-tunnel-config() {
    local port=$1
    local nickname=${2:-docker-agent}
    local host_name=${3:-localhost}
    local known_hosts=~/.ssh/docker-agent/known_hosts
    local cm_sockets=~/.ssh/docker-agent/cm_sockets
    mkdir -p $(dirname "$known_hosts") $cm_sockets

    ssh-keyscan -p $port $host_name > $known_hosts 2> /dev/null

    cat <<EOF
host $nickname
    User root
    HostName $host_name
    Port $port
    ControlMaster auto
    ControlPath $cm_sockets/%r@%h:%p
    UserKnownHostsFile $known_hosts
    ForwardAgent true
EOF
}

docker-agent-tunnel-start() {
    local nickname=${1:-docker-agent}

    ssh -f -F $DOCKER_AGENT_CONFIG $nickname \
        'ln -fs $SSH_AUTH_SOCK /tmp/ssh-auth-sock; tail -f /dev/null'
}

docker-agent-tunnel-stop() {
    local nickname=${1:-docker-agent}
    ssh -F $DOCKER_AGENT_CONFIG -O exit $nickname 2>/dev/null
}

docker-agent-tunnel-status() {
    local nickname=${1:-docker-agent}
    local msg=''
    if ssh -F $DOCKER_AGENT_CONFIG -O check $nickname 2>/dev/null ; then
        msg='docker-agent ssh tunnel is running'
    else
        msg='docker-agent ssh tunnel is NOT running'
    fi
    printf "%s\n" "$msg"
}

docker-agent-ls-volume() {
    docker run \
           --rm \
           --entrypoint '' \
           -v docker-agent-tmp:/tmp \
           dobbs/docker-agent \
           ls -al /tmp
}

docker-agent-long-status() {
    printf "%s\n" \
           '' \
           '========================' \
           'status' \
           '========================' \
           'ls -al docker-agent-tmp' \
           "$(docker-agent-ls-volume)" \
           '' \
           "$(docker-agent-sshd-status)" \
           "$(docker-agent-tunnel-status)" \
           '' \
           'run docker-agent-destroy to shutdown the agent and unload the functions'
}

docker-agent-commands() {
    declare -f | grep ^docker-agent-
}

docker-agent-main() {
    DOCKER_AGENT_CONFIG=~/.ssh/docker-agent/config

    docker-agent-tunnel-stop
    docker-agent-sshd-stop
    local ssh_port=$(docker-agent-sshd-start)
    docker-agent-tunnel-config $ssh_port > $DOCKER_AGENT_CONFIG
    docker-agent-tunnel-start
    docker-agent-long-status
}

docker-agent-destroy() {
    printf "%s\n" \
           '' \
           'docker-agent-tunnel-stop' \
           'docker-agent-sshd-stop' \
           "$(declare -f | awk '/^docker-agent-/ {print $1}' | xargs echo unset -f)" \
           'unset DOCKER_AGENT_CONFIG' \
           'docker volume rm docker-agent-tmp' \
           '' \
           '# now that you know what this does, make it so:' \
           '# eval "$(docker-agent-destroy)"'
}

docker-agent-main

# now that you've looked at what this does, you can invoke it
# eval \"\$(docker run --rm dobbs/docker-agent)\"
